services:
  postgres:
    image: postgres:17
    restart: unless-stopped
    container_name: postgres
    environment:
      POSTGRES_DB: pharmadb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d pharmadb"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    image: pharma-api
    restart: unless-stopped
    container_name: pharma-api
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    environment:
      # Écrase les URLs du .env pour pointer vers le service postgres
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@postgres:5432/pharmadb
      DATABASE_URL_SYNC: postgresql://postgres:postgres@postgres:5432/pharmadb
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
