apiVersion: v1
kind: Secret
metadata:
  name: ovh-credentials
  namespace: external-secrets
type: Opaque
data:
  application-key: <app_key>
  application-secret: <app_secret>
  consumer-key: <consumer_key>

---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: ovhcloud-store
spec:
  provider:
      vault:
        server: "https://<region>.okms.ovh.net/api/<consumer_key_with_->"  
        path: "secret"
        version: "v2" 
        auth:
            tokenSecretRef:
              name: ovhcloud-vault-token 
              key: token
              namespace: external-secrets
